export const emojis = [
  { char: "😃", name: "grinning face with big eyes", subgroup: "face-smiling" },
  {
    char: "😄",
    name: "grinning face with smiling eyes",
    subgroup: "face-smiling",
  },
  {
    char: "😁",
    name: "beaming face with smiling eyes",
    subgroup: "face-smiling",
  },
  { char: "😆", name: "grinning squinting face", subgroup: "face-smiling" },
  { char: "😅", name: "grinning face with sweat", subgroup: "face-smiling" },
  {
    char: "🤣",
    name: "rolling on the floor laughing",
    subgroup: "face-smiling",
  },
  { char: "😂", name: "face with tears of joy", subgroup: "face-smiling" },
  { char: "🙂", name: "slightly smiling face", subgroup: "face-smiling" },
  { char: "🙃", name: "upside-down face", subgroup: "face-smiling" },
  { char: "😉", name: "winking face", subgroup: "face-smiling" },
  {
    char: "😊",
    name: "smiling face with smiling eyes",
    subgroup: "face-smiling",
  },
  { char: "😇", name: "smiling face with halo", subgroup: "face-smiling" },
  { char: "🥰", name: "smiling face with hearts", subgroup: "face-affection" },
  {
    char: "😍",
    name: "smiling face with heart-eyes",
    subgroup: "face-affection",
  },
  { char: "🤩", name: "star-struck", subgroup: "face-affection" },
  { char: "😘", name: "face blowing a kiss", subgroup: "face-affection" },
  { char: "😗", name: "kissing face", subgroup: "face-affection" },
  { char: "☺️", name: "smiling face", subgroup: "face-affection" },
  { char: "☺", name: "smiling face", subgroup: "face-affection" },
  {
    char: "😚",
    name: "kissing face with closed eyes",
    subgroup: "face-affection",
  },
  {
    char: "😙",
    name: "kissing face with smiling eyes",
    subgroup: "face-affection",
  },
  { char: "🥲", name: "smiling face with tear", subgroup: "face-affection" },
  { char: "😋", name: "face savoring food", subgroup: "face-tongue" },
  { char: "😛", name: "face with tongue", subgroup: "face-tongue" },
  { char: "😜", name: "winking face with tongue", subgroup: "face-tongue" },
  { char: "🤪", name: "zany face", subgroup: "face-tongue" },
  { char: "😝", name: "squinting face with tongue", subgroup: "face-tongue" },
  { char: "🤑", name: "money-mouth face", subgroup: "face-tongue" },
  { char: "🤗", name: "hugging face", subgroup: "face-hand" },
  { char: "🤭", name: "face with hand over mouth", subgroup: "face-hand" },
  { char: "🤫", name: "shushing face", subgroup: "face-hand" },
  { char: "🤔", name: "thinking face", subgroup: "face-hand" },
  { char: "🤐", name: "zipper-mouth face", subgroup: "face-neutral-skeptical" },
  {
    char: "🤨",
    name: "face with raised eyebrow",
    subgroup: "face-neutral-skeptical",
  },
  { char: "😐", name: "neutral face", subgroup: "face-neutral-skeptical" },
  {
    char: "😑",
    name: "expressionless face",
    subgroup: "face-neutral-skeptical",
  },
  {
    char: "😶",
    name: "face without mouth",
    subgroup: "face-neutral-skeptical",
  },
  { char: "😶‍🌫️", name: "face in clouds", subgroup: "face-neutral-skeptical" },
  { char: "😶‍🌫", name: "face in clouds", subgroup: "face-neutral-skeptical" },
  { char: "😏", name: "smirking face", subgroup: "face-neutral-skeptical" },
  { char: "😒", name: "unamused face", subgroup: "face-neutral-skeptical" },
  {
    char: "🙄",
    name: "face with rolling eyes",
    subgroup: "face-neutral-skeptical",
  },
  { char: "😬", name: "grimacing face", subgroup: "face-neutral-skeptical" },
  { char: "🤥", name: "lying face", subgroup: "face-neutral-skeptical" },
  { char: "😌", name: "relieved face", subgroup: "face-sleepy" },
  { char: "😔", name: "pensive face", subgroup: "face-sleepy" },
  { char: "😪", name: "sleepy face", subgroup: "face-sleepy" },
  { char: "🤤", name: "drooling face", subgroup: "face-sleepy" },
  { char: "😴", name: "sleeping face", subgroup: "face-sleepy" },
  { char: "😷", name: "face with medical mask", subgroup: "face-unwell" },
  { char: "🤒", name: "face with thermometer", subgroup: "face-unwell" },
  { char: "🤕", name: "face with head-bandage", subgroup: "face-unwell" },
  { char: "🤢", name: "nauseated face", subgroup: "face-unwell" },
  { char: "🤮", name: "face vomiting", subgroup: "face-unwell" },
  { char: "🤧", name: "sneezing face", subgroup: "face-unwell" },
  { char: "🥵", name: "hot face", subgroup: "face-unwell" },
  { char: "🥶", name: "cold face", subgroup: "face-unwell" },
  { char: "🥴", name: "woozy face", subgroup: "face-unwell" },
  { char: "😵", name: "knocked-out face", subgroup: "face-unwell" },
  { char: "😵‍💫", name: "face with spiral eyes", subgroup: "face-unwell" },
  { char: "🤯", name: "exploding head", subgroup: "face-unwell" },
  { char: "🤠", name: "cowboy hat face", subgroup: "face-hat" },
  { char: "🥳", name: "partying face", subgroup: "face-hat" },
  { char: "🥸", name: "disguised face", subgroup: "face-hat" },
  {
    char: "😎",
    name: "smiling face with sunglasses",
    subgroup: "face-glasses",
  },
  { char: "🤓", name: "nerd face", subgroup: "face-glasses" },
  { char: "🧐", name: "face with monocle", subgroup: "face-glasses" },
  { char: "😕", name: "confused face", subgroup: "face-concerned" },
  { char: "😟", name: "worried face", subgroup: "face-concerned" },
  { char: "🙁", name: "slightly frowning face", subgroup: "face-concerned" },
  { char: "☹️", name: "frowning face", subgroup: "face-concerned" },
  { char: "☹", name: "frowning face", subgroup: "face-concerned" },
  { char: "😮", name: "face with open mouth", subgroup: "face-concerned" },
  { char: "😯", name: "hushed face", subgroup: "face-concerned" },
  { char: "😲", name: "astonished face", subgroup: "face-concerned" },
  { char: "😳", name: "flushed face", subgroup: "face-concerned" },
  { char: "🥺", name: "pleading face", subgroup: "face-concerned" },
  {
    char: "😦",
    name: "frowning face with open mouth",
    subgroup: "face-concerned",
  },
  { char: "😧", name: "anguished face", subgroup: "face-concerned" },
  { char: "😨", name: "fearful face", subgroup: "face-concerned" },
  { char: "😰", name: "anxious face with sweat", subgroup: "face-concerned" },
  { char: "😥", name: "sad but relieved face", subgroup: "face-concerned" },
  { char: "😢", name: "crying face", subgroup: "face-concerned" },
  { char: "😭", name: "loudly crying face", subgroup: "face-concerned" },
  { char: "😱", name: "face screaming in fear", subgroup: "face-concerned" },
  { char: "😖", name: "confounded face", subgroup: "face-concerned" },
  { char: "😣", name: "persevering face", subgroup: "face-concerned" },
  { char: "😞", name: "disappointed face", subgroup: "face-concerned" },
  { char: "😓", name: "downcast face with sweat", subgroup: "face-concerned" },
  { char: "😩", name: "weary face", subgroup: "face-concerned" },
  { char: "😫", name: "tired face", subgroup: "face-concerned" },
  { char: "🥱", name: "yawning face", subgroup: "face-concerned" },
  { char: "😤", name: "face with steam from nose", subgroup: "face-negative" },
  { char: "😡", name: "pouting face", subgroup: "face-negative" },
  { char: "😠", name: "angry face", subgroup: "face-negative" },
  { char: "🤬", name: "face with symbols on mouth", subgroup: "face-negative" },
  { char: "😈", name: "smiling face with horns", subgroup: "face-negative" },
  { char: "👿", name: "angry face with horns", subgroup: "face-negative" },
  { char: "💀", name: "skull", subgroup: "face-negative" },
  { char: "☠️", name: "skull and crossbones", subgroup: "face-negative" },
  { char: "☠", name: "skull and crossbones", subgroup: "face-negative" },
  { char: "💩", name: "pile of poo", subgroup: "face-costume" },
  { char: "🤡", name: "clown face", subgroup: "face-costume" },
  { char: "👹", name: "ogre", subgroup: "face-costume" },
  { char: "👺", name: "goblin", subgroup: "face-costume" },
  { char: "👻", name: "ghost", subgroup: "face-costume" },
  { char: "👽", name: "alien", subgroup: "face-costume" },
  { char: "👾", name: "alien monster", subgroup: "face-costume" },
  { char: "🤖", name: "robot", subgroup: "face-costume" },
  { char: "😺", name: "grinning cat", subgroup: "cat-face" },
  { char: "😸", name: "grinning cat with smiling eyes", subgroup: "cat-face" },
  { char: "😹", name: "cat with tears of joy", subgroup: "cat-face" },
  { char: "😻", name: "smiling cat with heart-eyes", subgroup: "cat-face" },
  { char: "😼", name: "cat with wry smile", subgroup: "cat-face" },
  { char: "😽", name: "kissing cat", subgroup: "cat-face" },
  { char: "🙀", name: "weary cat", subgroup: "cat-face" },
  { char: "😿", name: "crying cat", subgroup: "cat-face" },
  { char: "😾", name: "pouting cat", subgroup: "cat-face" },
  { char: "🙈", name: "see-no-evil monkey", subgroup: "monkey-face" },
  { char: "🙉", name: "hear-no-evil monkey", subgroup: "monkey-face" },
  { char: "🙊", name: "speak-no-evil monkey", subgroup: "monkey-face" },
  { char: "💋", name: "kiss mark", subgroup: "emotion" },
  { char: "💌", name: "love letter", subgroup: "emotion" },
  { char: "💘", name: "heart with arrow", subgroup: "emotion" },
  { char: "💝", name: "heart with ribbon", subgroup: "emotion" },
  { char: "💖", name: "sparkling heart", subgroup: "emotion" },
  { char: "💗", name: "growing heart", subgroup: "emotion" },
  { char: "💓", name: "beating heart", subgroup: "emotion" },
  { char: "💞", name: "revolving hearts", subgroup: "emotion" },
  { char: "💕", name: "two hearts", subgroup: "emotion" },
  { char: "💟", name: "heart decoration", subgroup: "emotion" },
  { char: "❣️", name: "heart exclamation", subgroup: "emotion" },
  { char: "❣", name: "heart exclamation", subgroup: "emotion" },
  { char: "💔", name: "broken heart", subgroup: "emotion" },
  { char: "❤️‍🔥", name: "heart on fire", subgroup: "emotion" },
  { char: "❤‍🔥", name: "heart on fire", subgroup: "emotion" },
  { char: "❤️‍🩹", name: "mending heart", subgroup: "emotion" },
  { char: "❤‍🩹", name: "mending heart", subgroup: "emotion" },
  { char: "❤️", name: "red heart", subgroup: "emotion" },
  { char: "❤", name: "red heart", subgroup: "emotion" },
  { char: "🧡", name: "orange heart", subgroup: "emotion" },
  { char: "💛", name: "yellow heart", subgroup: "emotion" },
  { char: "💚", name: "green heart", subgroup: "emotion" },
  { char: "💙", name: "blue heart", subgroup: "emotion" },
  { char: "💜", name: "purple heart", subgroup: "emotion" },
  { char: "🤎", name: "brown heart", subgroup: "emotion" },
  { char: "🖤", name: "black heart", subgroup: "emotion" },
  { char: "🤍", name: "white heart", subgroup: "emotion" },
  { char: "💯", name: "hundred points", subgroup: "emotion" },
  { char: "💢", name: "anger symbol", subgroup: "emotion" },
  { char: "💥", name: "collision", subgroup: "emotion" },
  { char: "💫", name: "dizzy", subgroup: "emotion" },
  { char: "💦", name: "sweat droplets", subgroup: "emotion" },
  { char: "💨", name: "dashing away", subgroup: "emotion" },
  { char: "🕳️", name: "hole", subgroup: "emotion" },
  { char: "🕳", name: "hole", subgroup: "emotion" },
  { char: "💣", name: "bomb", subgroup: "emotion" },
  { char: "💬", name: "speech balloon", subgroup: "emotion" },
  { char: "👁️‍🗨️", name: "eye in speech bubble", subgroup: "emotion" },
  { char: "👁‍🗨️", name: "eye in speech bubble", subgroup: "emotion" },
  { char: "👁️‍🗨", name: "eye in speech bubble", subgroup: "emotion" },
  { char: "👁‍🗨", name: "eye in speech bubble", subgroup: "emotion" },
  { char: "🗨️", name: "left speech bubble", subgroup: "emotion" },
  { char: "🗨", name: "left speech bubble", subgroup: "emotion" },
  { char: "🗯️", name: "right anger bubble", subgroup: "emotion" },
  { char: "🗯", name: "right anger bubble", subgroup: "emotion" },
  { char: "💭", name: "thought balloon", subgroup: "emotion" },
  { char: "💤", name: "zzz", subgroup: "emotion" },
  { char: "👋", name: "waving hand", subgroup: "hand-fingers-open" },
  { char: "🤚", name: "raised back of hand", subgroup: "hand-fingers-open" },
  {
    char: "🖐️",
    name: "hand with fingers splayed",
    subgroup: "hand-fingers-open",
  },
  {
    char: "🖐",
    name: "hand with fingers splayed",
    subgroup: "hand-fingers-open",
  },
  { char: "✋", name: "raised hand", subgroup: "hand-fingers-open" },
  { char: "🖖", name: "vulcan salute", subgroup: "hand-fingers-open" },
  { char: "👌", name: "OK hand", subgroup: "hand-fingers-partial" },
  { char: "🤌", name: "pinched fingers", subgroup: "hand-fingers-partial" },
  { char: "🤏", name: "pinching hand", subgroup: "hand-fingers-partial" },
  { char: "✌️", name: "victory hand", subgroup: "hand-fingers-partial" },
  { char: "✌", name: "victory hand", subgroup: "hand-fingers-partial" },
  { char: "🤞", name: "crossed fingers", subgroup: "hand-fingers-partial" },
  { char: "🤟", name: "love-you gesture", subgroup: "hand-fingers-partial" },
  { char: "🤘", name: "sign of the horns", subgroup: "hand-fingers-partial" },
  { char: "🤙", name: "call me hand", subgroup: "hand-fingers-partial" },
  {
    char: "👈",
    name: "backhand index pointing left",
    subgroup: "hand-single-finger",
  },
  {
    char: "👉",
    name: "backhand index pointing right",
    subgroup: "hand-single-finger",
  },
  {
    char: "👆",
    name: "backhand index pointing up",
    subgroup: "hand-single-finger",
  },
  { char: "🖕", name: "middle finger", subgroup: "hand-single-finger" },
  {
    char: "👇",
    name: "backhand index pointing down",
    subgroup: "hand-single-finger",
  },
  { char: "☝️", name: "index pointing up", subgroup: "hand-single-finger" },
  { char: "☝", name: "index pointing up", subgroup: "hand-single-finger" },
  { char: "👍", name: "thumbs up", subgroup: "hand-fingers-closed" },
  { char: "👎", name: "thumbs down", subgroup: "hand-fingers-closed" },
  { char: "✊", name: "raised fist", subgroup: "hand-fingers-closed" },
  { char: "👊", name: "oncoming fist", subgroup: "hand-fingers-closed" },
  { char: "🤛", name: "left-facing fist", subgroup: "hand-fingers-closed" },
  { char: "🤜", name: "right-facing fist", subgroup: "hand-fingers-closed" },
  { char: "👏", name: "clapping hands", subgroup: "hands" },
  { char: "🙌", name: "raising hands", subgroup: "hands" },
  { char: "👐", name: "open hands", subgroup: "hands" },
  { char: "🤲", name: "palms up together", subgroup: "hands" },
  { char: "🤝", name: "handshake", subgroup: "hands" },
  { char: "🙏", name: "folded hands", subgroup: "hands" },
  { char: "✍️", name: "writing hand", subgroup: "hand-prop" },
  { char: "✍", name: "writing hand", subgroup: "hand-prop" },
  { char: "💅", name: "nail polish", subgroup: "hand-prop" },
  { char: "🤳", name: "selfie", subgroup: "hand-prop" },
  { char: "💪", name: "flexed biceps", subgroup: "body-parts" },
  { char: "🦾", name: "mechanical arm", subgroup: "body-parts" },
  { char: "🦿", name: "mechanical leg", subgroup: "body-parts" },
  { char: "🦵", name: "leg", subgroup: "body-parts" },
  { char: "🦶", name: "foot", subgroup: "body-parts" },
  { char: "👂", name: "ear", subgroup: "body-parts" },
  { char: "🦻", name: "ear with hearing aid", subgroup: "body-parts" },
  { char: "👃", name: "nose", subgroup: "body-parts" },
  { char: "🧠", name: "brain", subgroup: "body-parts" },
  { char: "🫀", name: "anatomical heart", subgroup: "body-parts" },
  { char: "🫁", name: "lungs", subgroup: "body-parts" },
  { char: "🦷", name: "tooth", subgroup: "body-parts" },
  { char: "🦴", name: "bone", subgroup: "body-parts" },
  { char: "👀", name: "eyes", subgroup: "body-parts" },
  { char: "👁️", name: "eye", subgroup: "body-parts" },
  { char: "👁", name: "eye", subgroup: "body-parts" },
  { char: "👅", name: "tongue", subgroup: "body-parts" },
  { char: "👄", name: "mouth", subgroup: "body-parts" },
  { char: "🦰", name: "red hair", subgroup: "hair-style" },
  { char: "🦱", name: "curly hair", subgroup: "hair-style" },
  { char: "🦳", name: "white hair", subgroup: "hair-style" },
  { char: "🦲", name: "bald", subgroup: "hair-style" },
  { char: "🐸", name: "frog", subgroup: "animal-amphibian" },
  { char: "🍦", name: "soft ice cream", subgroup: "food-sweet" },
  { char: "🍧", name: "shaved ice", subgroup: "food-sweet" },
  { char: "🍨", name: "ice cream", subgroup: "food-sweet" },
  { char: "🍩", name: "doughnut", subgroup: "food-sweet" },
  { char: "🍪", name: "cookie", subgroup: "food-sweet" },
  { char: "🎂", name: "birthday cake", subgroup: "food-sweet" },
  { char: "🍰", name: "shortcake", subgroup: "food-sweet" },
  { char: "🧁", name: "cupcake", subgroup: "food-sweet" },
  { char: "🥧", name: "pie", subgroup: "food-sweet" },
  { char: "🍫", name: "chocolate bar", subgroup: "food-sweet" },
  { char: "🍬", name: "candy", subgroup: "food-sweet" },
  { char: "🍭", name: "lollipop", subgroup: "food-sweet" },
  { char: "🍮", name: "custard", subgroup: "food-sweet" },
  { char: "🍯", name: "honey pot", subgroup: "food-sweet" },
  { char: "🛎️", name: "bellhop bell", subgroup: "hotel" },
  { char: "🛎", name: "bellhop bell", subgroup: "hotel" },
  { char: "🧳", name: "luggage", subgroup: "hotel" },
  { char: "🎖️", name: "military medal", subgroup: "award-medal" },
  { char: "🎖", name: "military medal", subgroup: "award-medal" },
  { char: "🏆", name: "trophy", subgroup: "award-medal" },
  { char: "🏅", name: "sports medal", subgroup: "award-medal" },
  { char: "🥇", name: "1st place medal", subgroup: "award-medal" },
  { char: "🥈", name: "2nd place medal", subgroup: "award-medal" },
  { char: "🥉", name: "3rd place medal", subgroup: "award-medal" },
  { char: "🎭", name: "performing arts", subgroup: "arts & crafts" },
  { char: "🖼️", name: "framed picture", subgroup: "arts & crafts" },
  { char: "🖼", name: "framed picture", subgroup: "arts & crafts" },
  { char: "🎨", name: "artist palette", subgroup: "arts & crafts" },
  { char: "🧵", name: "thread", subgroup: "arts & crafts" },
  { char: "🪡", name: "sewing needle", subgroup: "arts & crafts" },
  { char: "🧶", name: "yarn", subgroup: "arts & crafts" },
  { char: "🪢", name: "knot", subgroup: "arts & crafts" },
  { char: "🔇", name: "muted speaker", subgroup: "sound" },
  { char: "🔈", name: "speaker low volume", subgroup: "sound" },
  { char: "🔉", name: "speaker medium volume", subgroup: "sound" },
  { char: "🔊", name: "speaker high volume", subgroup: "sound" },
  { char: "📢", name: "loudspeaker", subgroup: "sound" },
  { char: "📣", name: "megaphone", subgroup: "sound" },
  { char: "📯", name: "postal horn", subgroup: "sound" },
  { char: "🔔", name: "bell", subgroup: "sound" },
  { char: "🔕", name: "bell with slash", subgroup: "sound" },
  { char: "💰", name: "money bag", subgroup: "money" },
  { char: "🪙", name: "coin", subgroup: "money" },
  { char: "💴", name: "yen banknote", subgroup: "money" },
  { char: "💵", name: "dollar banknote", subgroup: "money" },
  { char: "💶", name: "euro banknote", subgroup: "money" },
  { char: "💷", name: "pound banknote", subgroup: "money" },
  { char: "💸", name: "money with wings", subgroup: "money" },
  { char: "💳", name: "credit card", subgroup: "money" },
  { char: "🧾", name: "receipt", subgroup: "money" },
  { char: "💹", name: "chart increasing with yen", subgroup: "money" },
  { char: "✉️", name: "envelope", subgroup: "mail" },
  { char: "✉", name: "envelope", subgroup: "mail" },
  { char: "📧", name: "e-mail", subgroup: "mail" },
  { char: "📨", name: "incoming envelope", subgroup: "mail" },
  { char: "📩", name: "envelope with arrow", subgroup: "mail" },
  { char: "📤", name: "outbox tray", subgroup: "mail" },
  { char: "📥", name: "inbox tray", subgroup: "mail" },
  { char: "📦", name: "package", subgroup: "mail" },
  { char: "📫", name: "closed mailbox with raised flag", subgroup: "mail" },
  { char: "📪", name: "closed mailbox with lowered flag", subgroup: "mail" },
  { char: "📬", name: "open mailbox with raised flag", subgroup: "mail" },
  { char: "📭", name: "open mailbox with lowered flag", subgroup: "mail" },
  { char: "📮", name: "postbox", subgroup: "mail" },
  { char: "🗳️", name: "ballot box with ballot", subgroup: "mail" },
  { char: "🗳", name: "ballot box with ballot", subgroup: "mail" },
  { char: "✏️", name: "pencil", subgroup: "writing" },
  { char: "✏", name: "pencil", subgroup: "writing" },
  { char: "✒️", name: "black nib", subgroup: "writing" },
  { char: "✒", name: "black nib", subgroup: "writing" },
  { char: "🖋️", name: "fountain pen", subgroup: "writing" },
  { char: "🖋", name: "fountain pen", subgroup: "writing" },
  { char: "🖊️", name: "pen", subgroup: "writing" },
  { char: "🖊", name: "pen", subgroup: "writing" },
  { char: "🖌️", name: "paintbrush", subgroup: "writing" },
  { char: "🖌", name: "paintbrush", subgroup: "writing" },
  { char: "🖍️", name: "crayon", subgroup: "writing" },
  { char: "🖍", name: "crayon", subgroup: "writing" },
  { char: "📝", name: "memo", subgroup: "writing" },
  { char: "🔒", name: "locked", subgroup: "lock" },
  { char: "🔓", name: "unlocked", subgroup: "lock" },
  { char: "🔏", name: "locked with pen", subgroup: "lock" },
  { char: "🔐", name: "locked with key", subgroup: "lock" },
  { char: "🔑", name: "key", subgroup: "lock" },
  { char: "🗝️", name: "old key", subgroup: "lock" },
  { char: "🗝", name: "old key", subgroup: "lock" },
  { char: "🔨", name: "hammer", subgroup: "tool" },
  { char: "🪓", name: "axe", subgroup: "tool" },
  { char: "⛏️", name: "pick", subgroup: "tool" },
  { char: "⛏", name: "pick", subgroup: "tool" },
  { char: "⚒️", name: "hammer and pick", subgroup: "tool" },
  { char: "⚒", name: "hammer and pick", subgroup: "tool" },
  { char: "🛠️", name: "hammer and wrench", subgroup: "tool" },
  { char: "🛠", name: "hammer and wrench", subgroup: "tool" },
  { char: "🗡️", name: "dagger", subgroup: "tool" },
  { char: "🗡", name: "dagger", subgroup: "tool" },
  { char: "⚔️", name: "crossed swords", subgroup: "tool" },
  { char: "⚔", name: "crossed swords", subgroup: "tool" },
  { char: "🔫", name: "water pistol", subgroup: "tool" },
  { char: "🪃", name: "boomerang", subgroup: "tool" },
  { char: "🏹", name: "bow and arrow", subgroup: "tool" },
  { char: "🛡️", name: "shield", subgroup: "tool" },
  { char: "🛡", name: "shield", subgroup: "tool" },
  { char: "🪚", name: "carpentry saw", subgroup: "tool" },
  { char: "🔧", name: "wrench", subgroup: "tool" },
  { char: "🪛", name: "screwdriver", subgroup: "tool" },
  { char: "🔩", name: "nut and bolt", subgroup: "tool" },
  { char: "⚙️", name: "gear", subgroup: "tool" },
  { char: "⚙", name: "gear", subgroup: "tool" },
  { char: "🗜️", name: "clamp", subgroup: "tool" },
  { char: "🗜", name: "clamp", subgroup: "tool" },
  { char: "⚖️", name: "balance scale", subgroup: "tool" },
  { char: "⚖", name: "balance scale", subgroup: "tool" },
  { char: "🦯", name: "white cane", subgroup: "tool" },
  { char: "🔗", name: "link", subgroup: "tool" },
  { char: "⛓️", name: "chains", subgroup: "tool" },
  { char: "⛓", name: "chains", subgroup: "tool" },
  { char: "🪝", name: "hook", subgroup: "tool" },
  { char: "🧰", name: "toolbox", subgroup: "tool" },
  { char: "🧲", name: "magnet", subgroup: "tool" },
  { char: "🪜", name: "ladder", subgroup: "tool" },
  { char: "💉", name: "syringe", subgroup: "medical" },
  { char: "🩸", name: "drop of blood", subgroup: "medical" },
  { char: "💊", name: "pill", subgroup: "medical" },
  { char: "🩹", name: "adhesive bandage", subgroup: "medical" },
  { char: "🩺", name: "stethoscope", subgroup: "medical" },
  { char: "🚪", name: "door", subgroup: "household" },
  { char: "🛗", name: "elevator", subgroup: "household" },
  { char: "🪞", name: "mirror", subgroup: "household" },
  { char: "🪟", name: "window", subgroup: "household" },
  { char: "🛏️", name: "bed", subgroup: "household" },
  { char: "🛏", name: "bed", subgroup: "household" },
  { char: "🛋️", name: "couch and lamp", subgroup: "household" },
  { char: "🛋", name: "couch and lamp", subgroup: "household" },
  { char: "🪑", name: "chair", subgroup: "household" },
  { char: "🚽", name: "toilet", subgroup: "household" },
  { char: "🪠", name: "plunger", subgroup: "household" },
  { char: "🚿", name: "shower", subgroup: "household" },
  { char: "🛁", name: "bathtub", subgroup: "household" },
  { char: "🪤", name: "mouse trap", subgroup: "household" },
  { char: "🪒", name: "razor", subgroup: "household" },
  { char: "🧴", name: "lotion bottle", subgroup: "household" },
  { char: "🧷", name: "safety pin", subgroup: "household" },
  { char: "🧹", name: "broom", subgroup: "household" },
  { char: "🧺", name: "basket", subgroup: "household" },
  { char: "🧻", name: "roll of paper", subgroup: "household" },
  { char: "🪣", name: "bucket", subgroup: "household" },
  { char: "🧼", name: "soap", subgroup: "household" },
  { char: "🪥", name: "toothbrush", subgroup: "household" },
  { char: "🧽", name: "sponge", subgroup: "household" },
  { char: "🧯", name: "fire extinguisher", subgroup: "household" },
  { char: "🛒", name: "shopping cart", subgroup: "household" },
  { char: "🚬", name: "cigarette", subgroup: "other-object" },
  { char: "🏁", name: "chequered flag", subgroup: "flag" },
  { char: "🚩", name: "triangular flag", subgroup: "flag" },
  { char: "🎌", name: "crossed flags", subgroup: "flag" },
  { char: "🏴", name: "black flag", subgroup: "flag" },
  { char: "🏳️", name: "white flag", subgroup: "flag" },
];
